---

####################
# Install Storage Class
####################

- name: Add Storage Class configuration
  template:
    src: storage-class-aws-ebs-gp2.yaml.j2
    dest: /tmp/storage-class-aws-ebs-gp2.yaml
    mode: 644
  become: true

- name: Load storage class into configuration
  command: "kubectl create -f /tmp/storage-class-aws-ebs-gp2.yaml"
