---

####################
# Install Kibana
####################

- name: Add Kibana deployment configuration
  template:
    src: kibana-deployment.yaml.j2
    dest: /tmp/kibana-deployment.yaml
    mode: 644
  become: true

- name: Add Kibana service configuration
  template:
    src: kibana-service.yaml.j2
    dest: /tmp/kibana-service.yaml
    mode: 644
  become: true

- name: Launch Kibana service
  command: "kubectl create -f /tmp/kibana-service.yaml"

- name: Launch Kibana deployment
  command: "kubectl create -f /tmp/kibana-deployment.yaml"
